### ISSUE TITLE
DEPRECATION: Usage of `snapshot.constructor` is deprecated, use `snapshot.type` instead.

### ISSUE THREAD

**Issue by hussfelt** [kurko/ember-localstorage-adapter#111]
```
DEBUG: -------------------------------
DEBUG: Ember      : 1.11.1
DEBUG: Ember Data : 1.0.0-beta.16
DEBUG: jQuery     : 1.11.2
DEBUG: -------------------------------
```

DEPRECATION: Usage of `snapshot.constructor` is deprecated, use `snapshot.type` instead.
        at Object.__exports__.default.EmberObject.extend.replaceDeprecate.Ember.deprecate (<anonymous>:981:38)
        at Ember.defineProperty.get [as constructor] (http://localhost:4200/assets/vendor.js:70587:21)
        at CallSiteToString (native)
        at Object.__exports__.default.EmberObject.extend.replaceDeprecate.Ember.deprecate (<anonymous>:949:20)
        at ember$data$lib$system$snapshot$$Snapshot.get (http://localhost:4200/assets/vendor.js:70863:15)
        at DS.LSAdapter.DS.Adapter.extend.updateRecord (http://localhost:4200/assets/vendor.js:82138:23)
        at ember$data$lib$system$store$$_commit (http://localhost:4200/assets/vendor.js:74392:39)
        at null.<anonymous> (http://localhost:4200/assets/vendor.js:73652:28)
        at Array.forEach (native)

**Comment by hussfelt** [comment]
Closed with #110
